#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# JmxTrans
#
# chkconfig: 2345 89 9
# description: jmxtrans

source /etc/rc.d/init.d/functions
[ -e {{ jmxtrans_prefix }}/conf/jmxtrans-env.sh ] && source {{ jmxtrans_prefix }}/conf/jmxtrans-env.sh

SERVER_SCRIPT={{ jmxtrans_prefix }}/bin/jmxtrans.sh
RETVAL=0
PIDFILE=/var/run/jmxtrans/jmxtrans.pid
desc="JmxTrans daemon"

start() {
  echo -n $"Starting $desc (jmxtrans): "
  su - jmxtrans -c "${SERVER_SCRIPT} start"
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/jmxtrans
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc (jmxtrans): "
  su - jmxtrans -c "${SERVER_SCRIPT} stop"
  RETVAL=$?
  sleep 5
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/jmxtrans $PIDFILE
}

restart() {
  stop
  start
}

checkstatus(){
  status -p $PIDFILE jmxtrans
  RETVAL=$?
}

condrestart(){
  [ -e /var/lock/subsys/jmxtrans ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    exit 1
esac

exit $RETVAL
